### ISSUE TITLE
Foundational Work Tracking Issue

### ISSUE THREAD

**Issue by wycats** [tildeio/helix#31]
Tracked in #30 

- [ ] Static methods
- [ ] Constructor arguments
- [ ] Allocating Ruby wrapper in Rust (methods that need `Duration.new` in Rust)
- [ ] Chaining APIs (either via taking and returning &mut or via consumption-style chaining)
- [ ] Lifetime annotations on methods (`def something<'a>(&self, other &'a Other) -> &'a Other`)
- [ ] Numeric coercions (and specifically, dealing with overflow idiomatically)

Other important work items:

- [ ] Defining coercions for all of the primary Ruby types (related: #19)
- [ ] Taking Ruby objects (or hybrid objects) instead of coercing to Rust types in methods
- [ ] Ergonomic invocation of Ruby methods on Ruby objects
- [ ] Propagating Ruby exceptions through Rust (and properly handling unwinding)
- [ ] Raising exceptions when type checking fails (currently we log the failure and return nil)
- [ ] Dynamically enforced ownership, `&T` and `&mut T` (similar to RefCell)
- [ ] Allowing access to the internals of basic Ruby types (like String) and locking further access to those values (options: freeze, lock the VM, ...)
- [ ] Ergonomically creating Ruby method wrappers for complex features like keyword arguments.
- [ ] Idioms for calling into Rust and trying a pure Ruby implementation if type checking fails (via `prepend` probably, for completeness when porting a pure-Ruby API with non-performant edge-cases, for example when types rely on Bignum overflow).
